### ISSUE TITLE
Cleanup swallows exit codes

### ISSUE THREAD

**Issue by r-vdp** [numtide/github-deploy#59]
**Describe the bug**

When doing `github-deploy cleanup <...> -- cmd` and `cmd` exits uncleanly, github-deploy swallows the exit code and exits cleanly.
This makes it hard to know that something went wrong and makes things like github actions show green checks while actually there was a failure.

This happens because the main loop in the code for cleanup does check the exit code, but when it's non-zero it just logs a message and continues, without tracking the fact that there was a failure.

**To Reproduce**

1. ...
2. ...

**Expected behavior**

Exit uncleanly if at least one action didn't exit cleanly.

**System information**

**Additional context**

**Comment by zimbatm** [comment]
What error did you see exactly?

It would help because `log.Fatalf` also exits the process with an error code.

**Comment by r-vdp** [comment]
The invoked command was Terraform (wrapped in just and terragrunt), which failed during planning. I can check what's the exact exit code that gets returned, but it's definitely not 0.

**Comment by zimbatm** [comment]
Ok, let me know
